#!/usr/bin/env sh

# Typecheck backend and frontend
cd backend && npx tsc --noEmit || exit 1
cd ../frontend && npx tsc --noEmit || exit 1
cd ..

# Lint backend and frontend
cd backend && npx eslint src/ || exit 1
cd ../frontend && npx next lint || exit 1
